### ISSUE TITLE
Non-disabled Google Play system update

### ISSUE THREAD

**Issue by Nyvronis** [TOMMYGUISEPE/LICH-ROM#1]
BUG: Updates are not being disabled via the path - Settings > Security and Privacy > Updates > Google Play System Update. Downloading this update and rebooting causes the smartphone to enter a bootloop.

Temp solution: Avoid updating, but if the update has already been downloaded - reboot in safe mode, and the update will be reset.

**Comment by SoheilFM** [comment]
is That for Port a54 or Port S21?Or Both?

**Comment by Nyvronis** [comment]
> is That for Port a54 or Port S21?Or Both?

All my issue for port s21fe

**Comment by Nyvronis** [comment]
//not relevant
